/***************************************************************************
 *   eu12.c                                   Version 20171130.122700      *
 *                                                                         *
 *   euler 1                                                               *
 *   Copyright (C) 2017         by Erick Antunes Teixeira                  *
 ***************************************************************************
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; version 2 of the License.               *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************
 *   To contact the author, please write to:                               *
 *   Erick Antunes Teixeira                                                *
 *   Email: erickantunest@gmail.com                                        *
 *   Webpage: http://www.upe.br                                            *
 *   Phone: +55 (81) 98765-4321                                            *
 ***************************************************************************/

/*
 * Instrucoes para compilar:
 *   $gcc eu1.c -o eu1.x -Wall
 *        -Wextra -ansi -pedantic-errors -g -O0 -DDEBUG=1
 */

/*
enunciado:
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:
1: 1
3: 1,3
6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/


/* ---------------------------------------------------------------------- */
/* includes */

#include <stdio.h> /* Standard I/O functions */
#include <stdlib.h> /* Miscellaneous functions (rand, malloc, srand)*/
#include <math.h> /* biblioteca que inclui funcoes matematicas, neste caso sera usado a funcao sqrt que tirara a raiz quadrada */

/* limits */
#define MAX 500

/* ---------------------------------------------------------------------- */
/* prototypes */

/* proposta: fazer um programa que ache a raiz quadrada do numero triangular feito pelo ultima vez, nisso qualquer numero que estiver abaixo da raiz que divide o numero triangular, certamente tem um multiplo acima que tambem faca o mesmo, alem disso a propria raiz tambem eh um divisor, dessa forma quando o numero de divisores for maior do que 500 o while ira ser quebrado e o ultimo numero triangular calculador tera mais de 500 divisores */

int main (void)
{
    int d=2; /* quantidade de divisores */
    int i=1; /* contador auxiliar */
    int e=0; /* contador auxiliar */
    int l; /* limite */
    int nt=1; /* numero triangular comecando em 1, poderia ser em outro valor mais na frente, mas a diferenca de tempo seria insignificante */


    while(d<=MAX)
    {
        d=2; /* vai redefinir ele proprio */
        i++;

        nt+=i; /* formacacao do numero triangular */
        l=sqrt(nt); 

        for(e=2; e<=l; e++)
        {
            if(!(nt%e))
            {
                if(e==l) /* esta eh a raiz quadrada para adicionar apenas uma 1 unidade aos divisores */
                    d++;
                else
                    d+=2;
            }
        }
    }


    printf("resposta: %d e seus divisores %d\n", nt, d);


    return 1;
}
/* ---------------------------------------------------------------------- */

/* ---------------------------------------------------------------------- */
/* vi: set ai et ts=4 sw=4 tw=0 wm=0 fo=croql : C config for Vim modeline */
/* Template by Dr. Beco <rcb at beco dot cc> Version 20160612.142044      */


